# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
dist: bionic

language: node_js
node_js:
  - 12
cache:
  - npm
  - pip

script:
  - bash pcbops-tryout/build.sh

after_success:
  - mkdir -p tmp
  - cd tmp
  -   cp ../travis-build-merger/_util/merge.py .
  -   cp ../travis-build-merger/_util/Pipfile .
  -   cp ../travis-build-merger/_util/Pipfile.lock .
  -   chmod +x merge.py
  -   sudo apt update
  -   sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  # pip3 install --user pipenv
  -  python3 -m pip install pipenv
  -  pipenv sync
  -  pipenv run python3 ./merge.py
  - cd -

after_failure:
  - cat /tmp/build.log
  - cat /tmp/merge.log

import:
  - credentials.yml
