# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

version: ~> 1.0

os: linux
dist: bionic

language: node_js

node_js:
  - 12

cache:
  - npm
  - pip

after_failure:
  - cat /tmp/build.log
  - cat /tmp/merge.log

import:
  - credentials.yml
  - .travis-merger.yml
  - .travis-stages.yml
  - pcbops-tryout/.travis.yml
